[project]
name = "pooling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cmcrameri>=1.9",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
]
